'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import ConnectCli from '../components/ConnectCli';
import AuthGate from '../components/AuthGate';
import AccountSettings from '../components/AccountSettings';

const flows = { gas: { label: 'Web App GAS', icon: 'G' }, migration: { label: 'Migrasi Next.js', icon: 'N' }, android: { label: 'Android Native', icon: 'A' } };
const fmt = value => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const pages = { '/': { key: 'overview', title: 'Ringkasan', eyebrow: 'WORKSPACE', heading: 'Kelola produk digital Anda.', description: 'Lihat status aplikasi, perangkat CLI, dan aktivitas terbaru dalam satu tempat.' }, '/buat-aplikasi': { key: 'create', title: 'Buat aplikasi', eyebrow: 'BUAT APLIKASI', heading: 'Mulai proyek baru.', description: 'Pilih jenis aplikasi dan biarkan CLI Anda menjalankan proses build.' }, '/aplikasi-saya': { key: 'apps', title: 'Aplikasi & web saya', eyebrow: 'PROYEK', heading: 'Semua aplikasi Anda.', description: 'Pantau antrean, build, deployment, serta hasil proyek yang pernah dibuat.' }, '/docs': { key: 'docs', title: 'Docs', eyebrow: 'PANDUAN', heading: 'Cara kerja WebToNative.', description: 'Ikuti panduan koneksi CLI dan alur pembuatan aplikasi.' }, '/pengaturan': { key: 'settings', title: 'Pengaturan', eyebrow: 'PENGATURAN', heading: 'Akun dan koneksi layanan.', description: 'Kelola keamanan akun, credential terenkripsi, dan perangkat Anda.' } };

function Workspace({ supabase, session }) {
  const pathname = usePathname(); const current = pages[pathname] || pages['/'];
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [agent, setAgent] = useState(null); const [theme, setTheme] = useState('light'); const [accountMenuOpen, setAccountMenuOpen] = useState(false); const [form, setForm] = useState({ name: '', flow: 'gas', template: 'auto', aiEnabled: true });
  const auth = { Authorization: `Bearer ${session.access_token}` };
  useEffect(() => { const next = localStorage.getItem('webtonative-theme') === 'dark' ? 'dark' : 'light'; setTheme(next); document.documentElement.dataset.theme = next; }, []);
  function toggleTheme() { const next = theme === 'dark' ? 'light' : 'dark'; setTheme(next); localStorage.setItem('webtonative-theme', next); document.documentElement.classList.remove('preview-theme-changing'); document.documentElement.dataset.theme = next; requestAnimationFrame(() => document.documentElement.classList.add('preview-theme-changing')); window.setTimeout(() => document.documentElement.classList.remove('preview-theme-changing'), 5000); }
  async function refresh() { setLoading(true); try { const response = await fetch('/api/jobs', { cache: 'no-store', headers: auth }); const payload = await response.json(); setJobs(payload.jobs || []); } catch { setMessage('Dashboard belum dapat terhubung ke API job.'); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, []);
  useEffect(() => { let live = true; const check = async () => { try { const response = await fetch('/api/agents/status', { cache: 'no-store', headers: auth }); const payload = await response.json(); if (live) setAgent(payload.active || null); } catch {} }; check(); const timer = setInterval(check, 5000); return () => { live = false; clearInterval(timer); }; }, []);
  async function submit(event) { event.preventDefault(); setMessage(''); const response = await fetch('/api/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json', ...auth }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error || 'Aplikasi gagal dibuat.'); setJobs(current => [payload.job, ...current]); setForm(current => ({ ...current, name: '' })); setMessage('Aplikasi ditambahkan ke antrean CLI milik akun Anda.'); }
  const counts = useMemo(() => ({ total: jobs.length, queued: jobs.filter(job => job.status === 'queued').length, ready: jobs.filter(job => job.status === 'ready' || job.status === 'success').length }), [jobs]);
  const nav = [['/', 'Ringkasan'], ['/buat-aplikasi', 'Buat aplikasi'], ['/aplikasi-saya', 'Aplikasi & web saya'], ['/docs', 'Docs']];
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">W</span><div><b>WebToNative</b><small>Workspace</small></div></div><nav aria-label="Navigasi utama">{nav.map(([href, label]) => <Link key={href} className={pathname === href ? 'active' : ''} href={href}>{label}</Link>)}</nav><div className={`connection ${agent ? 'connected' : ''}`}><span className="status-dot" />{agent ? `CLI ${agent.deviceName} aktif` : 'CLI belum terhubung'}<Link href="/">{agent ? 'Kelola perangkat' : 'Hubungkan CLI'}</Link></div><div className="sidebar-actions"><button className="theme-icon-button" type="button" onClick={toggleTheme} aria-label={theme === 'dark' ? 'Mode gelap aktif' : 'Mode terang aktif'}>{theme === 'dark' ? '◐' : '☀'}</button><div className="account-menu"><button className="gear-button" type="button" onClick={() => setAccountMenuOpen(value => !value)} aria-label="Menu akun" aria-expanded={accountMenuOpen}>⚙</button>{accountMenuOpen && <div className="account-popover"><Link href="/pengaturan" onClick={() => setAccountMenuOpen(false)}>Pengaturan</Link><button type="button" onClick={() => supabase.auth.signOut()}>Keluar akun</button></div>}</div></div></aside>
    <section className="workspace"><header><div><p className="eyebrow">{current.eyebrow}</p><h1>{current.heading}</h1><p>{current.description}</p></div><button className="outline" onClick={refresh}>Segarkan</button></header>
      {current.key === 'overview' && <><section className="metrics"><article><small>Total aplikasi</small><b>{counts.total}</b><span>Semua proyek Anda</span></article><article><small>Dalam antrean</small><b>{counts.queued}</b><span>Menunggu CLI</span></article><article><small>Siap diuji</small><b>{counts.ready}</b><span>Output tersedia</span></article></section><section className="connect-section"><ConnectCli token={session.access_token} /></section></>}
      {current.key === 'create' && <form className="panel create-job page-form" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">KONFIGURASI</p><h2>Detail aplikasi</h2></div><span className="chip">Build lokal</span></div><label>Nama aplikasi<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Contoh: Kasir Outlet Jakarta" required /></label><label>Jenis aplikasi<select value={form.flow} onChange={event => setForm({ ...form, flow: event.target.value })}>{Object.entries(flows).map(([key, flow]) => <option value={key} key={key}>{flow.label}</option>)}</select></label><label>Template<select value={form.template} onChange={event => setForm({ ...form, template: event.target.value })}><option value="auto">Pilih otomatis</option><option value="retail">Retail & Kasir</option><option value="service">Layanan & Booking</option><option value="education">Pendidikan</option></select></label><label className="toggle"><input type="checkbox" checked={form.aiEnabled} onChange={event => setForm({ ...form, aiEnabled: event.target.checked })} /><span>Gunakan AI untuk analisis kebutuhan</span></label><button className="primary" type="submit">Buat aplikasi <span>→</span></button>{message && <p className="message">{message}</p>}</form>}
      {current.key === 'apps' && <section className="panel job-panel"><div className="panel-heading"><div><p className="eyebrow">APLIKASI & WEB SAYA</p><h2>Proyek terbaru</h2></div><span className="chip">{loading ? 'Memuat…' : `${jobs.length} proyek`}</span></div><div className="job-list">{jobs.map(job => <article className="job" key={job.id}><span className={`job-icon ${job.flow}`}>{flows[job.flow]?.icon || '•'}</span><div><b>{job.name}</b><p>{flows[job.flow]?.label} · {fmt(job.createdAt)}</p><small>{job.note}</small></div><span className={`job-status ${job.status}`}>{job.status}</span></article>)}{!loading && !jobs.length && <p className="empty">Belum ada aplikasi. Buat aplikasi pertama Anda.</p>}</div></section>}
      {current.key === 'docs' && <section className="panel workflow docs-page"><p className="eyebrow">PANDUAN DASAR</p><h2>Mulai dalam tiga langkah</h2><ol><li><b>01</b><span>Di Ringkasan, hubungkan CLI pada komputer yang akan menjalankan build.</span></li><li><b>02</b><span>Buka Buat aplikasi, pilih jenis aplikasi, template, dan aktifkan AI bila diperlukan.</span></li><li><b>03</b><span>Buka Aplikasi & web saya untuk melihat status, link deployment, serta output build.</span></li></ol><p className="docs-note">Credential layanan disimpan terenkripsi melalui Pengaturan. Token tidak pernah ditampilkan kembali.</p></section>}
      {current.key === 'settings' && <AccountSettings supabase={supabase} session={session} />}
    </section></main>;
}
export default function Home() { return <AuthGate>{props => <Workspace {...props} />}</AuthGate>; }
