'use client';

import { useEffect, useState } from 'react';

const providers = { google_apps_script: 'Google Apps Script', vercel: 'Vercel', ai: 'AI Provider' };

export default function AccountSettings({ supabase, session }) {
  const [connections, setConnections] = useState([]); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ provider: 'google_apps_script', label: '', accountHint: '', secret: '' });
  const token = () => session.access_token;
  const request = (path, options = {}) => fetch(path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, ...(options.headers || {}) } });
  async function load() { const res = await request('/api/connections'); const data = await res.json(); if (res.ok) setConnections(data.connections || []); else setMessage(data.error); }
  useEffect(() => { load(); }, []);
  async function save(event) { event.preventDefault(); setMessage(''); const res = await request('/api/connections', { method: 'POST', body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) return setMessage(data.error); setConnections(current => [data.connection, ...current]); setForm({ provider: 'google_apps_script', label: '', accountHint: '', secret: '' }); setMessage('Koneksi disimpan terenkripsi. Credential tidak akan ditampilkan kembali.'); }
  async function remove(id) { if (!confirm('Putuskan koneksi ini? Credential terenkripsi akan dihapus dari akun Anda.')) return; const res = await request(`/api/connections/${id}`, { method: 'DELETE' }); if (res.ok) { setConnections(current => current.filter(item => item.id !== id)); setMessage('Koneksi berhasil dihapus.'); } }
  async function backup(id) { const backupPassword = prompt('Masukkan password backup minimal 10 karakter. File tidak dapat dipulihkan tanpa password ini.'); if (!backupPassword) return; const res = await request(`/api/connections/${id}/backup`, { method: 'POST', body: JSON.stringify({ backupPassword }) }); if (!res.ok) { const data = await res.json(); return setMessage(data.error); } const blob = await res.blob(); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = `webtonative-koneksi-${id}.json`; link.click(); URL.revokeObjectURL(href); setMessage('Backup terenkripsi berhasil diunduh. Simpan password backup secara aman.'); }
  async function changePassword(event) { event.preventDefault(); const nextPassword = new FormData(event.currentTarget).get('password'); const { error } = await supabase.auth.updateUser({ password: nextPassword }); setMessage(error ? error.message : 'Password akun diperbarui.'); event.currentTarget.reset(); }
  return <section id="pengaturan" className="settings-wrap"><div className="settings-heading"><div><p className="eyebrow">PENGATURAN AKUN</p><h2>Akun, keamanan, dan koneksi layanan</h2><p>{session.user.email} · credential disimpan terenkripsi.</p></div><button className="outline" onClick={() => supabase.auth.signOut()}>Keluar</button></div><div className="settings-grid"><article className="panel"><p className="eyebrow">KEAMANAN</p><h3>Password akun</h3><p className="muted">Gunakan minimal 8 karakter dan jangan bagikan akun Anda.</p><form onSubmit={changePassword}><label>Password baru<input name="password" type="password" minLength="8" required /></label><button className="outline" type="submit">Simpan password baru</button></form></article><article className="panel"><p className="eyebrow">KONEKSI BARU</p><h3>Tambah layanan</h3><form onSubmit={save}><label>Layanan<select value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })}>{Object.entries(providers).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Nama koneksi<input required placeholder="Contoh: Google bisnis utama" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} /></label><label>Akun / email / team<input required placeholder="Contoh: nama@gmail.com" value={form.accountHint} onChange={e => setForm({ ...form, accountHint: e.target.value })} /></label><label>Credential rahasia<input required type="password" placeholder="Token atau API key" value={form.secret} onChange={e => setForm({ ...form, secret: e.target.value })} /></label><button className="primary" type="submit">Simpan terenkripsi <span>→</span></button></form></article></div><section className="panel connections"><div className="panel-heading"><div><p className="eyebrow">KONEKSI TERSIMPAN</p><h3>Kelola akses layanan</h3></div><span className="chip">{connections.length} koneksi</span></div><p className="muted">Tombol unduh menghasilkan file JSON terenkripsi dengan password backup; token mentah tidak pernah ditampilkan.</p><div className="connection-list">{connections.map(item => <article className="stored-connection" key={item.id}><span className="provider-icon">{item.provider === 'vercel' ? '▲' : item.provider === 'ai' ? '✦' : 'G'}</span><div><b>{item.label}</b><small>{providers[item.provider]} · {item.account_hint}</small></div><div className="connection-actions"><button title="Unduh backup terenkripsi" className="icon-button" onClick={() => backup(item.id)}>↓</button><button title="Hapus koneksi" className="icon-button danger" onClick={() => remove(item.id)}>⌫</button></div></article>)}{!connections.length && <p className="empty">Belum ada koneksi. Tambahkan Google Apps Script, Vercel, atau AI Provider di atas.</p>}</div></section>{message && <p className="message">{message}</p>}</section>;
}
