import { getAppHtmlTemplate as getBaseAppHtmlTemplate } from './appHtmlV2.js';

const LAYOUT_CSS = `
/* Variasi tata letak dashboard per tema */
.dash-centered #dashboard{display:block!important}.dash-centered #sidebar{width:100%;min-height:auto;display:flex;align-items:center;gap:1.25rem;padding:1rem 2rem}.dash-centered #sidebar nav{display:flex;gap:.5rem;flex:1}.dash-centered #sidebar .menu{width:auto;padding:.65rem .9rem}.dash-centered #sidebar>div:last-child{margin:0!important;border:0!important;padding:0!important;display:flex;align-items:center;gap:.75rem}.dash-centered #userName{margin:0!important;white-space:nowrap}.dash-centered #logoutBtn{width:auto;white-space:nowrap}.dash-centered #dashboard>section{padding-top:3rem}
.dash-split-reverse #sidebar{order:2;box-shadow:-14px 0 35px rgba(15,23,42,.12)}.dash-split-reverse #dashboard>section{background:linear-gradient(135deg,#fff,transparent 55%)}
.dash-glass #dashboard{background:radial-gradient(circle at 10% 10%,var(--soft),transparent 32%),radial-gradient(circle at 88% 82%,color-mix(in srgb,var(--secondary) 18%,transparent),transparent 35%)}.dash-glass .card{background:rgba(255,255,255,.72);backdrop-filter:blur(16px);border-color:rgba(255,255,255,.55)}.dash-glass #sidebar{box-shadow:14px 0 42px rgba(15,23,42,.16)}
.dash-sidebar #sidebar{width:19rem}.dash-sidebar #dashboard>section{padding:2.5rem}.dash-sidebar .card{border-radius:1.75rem}
.dash-split #sidebar{width:15.5rem}.dash-split #dashboard>section{padding:3rem}.dash-split .card{box-shadow:0 24px 55px rgba(15,23,42,.11)}
.dash-workshop #dashboard{display:block!important;background:linear-gradient(135deg,#f8fafc,#fff7ed)}.dash-workshop #sidebar{width:100%;min-height:auto;display:flex;align-items:center;gap:1.25rem;padding:1rem 2rem;background:linear-gradient(90deg,#1c1917,#78350f,#b45309)}.dash-workshop #sidebar nav{display:flex;gap:.45rem;flex:1}.dash-workshop #sidebar .menu{width:auto;padding:.65rem .85rem}.dash-workshop #sidebar>div:last-child{margin:0!important;border:0!important;padding:0!important;display:flex;align-items:center;gap:.75rem}.dash-workshop #userName{margin:0!important;white-space:nowrap}.dash-workshop #logoutBtn{width:auto;white-space:nowrap}.dash-workshop #dashboard>section{padding-top:3rem}.dash-workshop .card{border-radius:1rem;border-top:4px solid #f59e0b}
@media(max-width:767px){.dash-centered #sidebar{display:block;padding:1.25rem}.dash-centered #sidebar nav{display:block;margin-top:1rem}.dash-centered #sidebar .menu{width:100%}.dash-centered #sidebar>div:last-child{display:block;margin-top:1.5rem!important}.dash-split-reverse #sidebar{order:0}}
/* Mobile-first: menu ringkas, form satu kolom, tabel tetap dapat digeser */
@media(max-width:767px){#dashboard{display:block!important}#sidebar{width:100%!important;min-height:auto!important;padding:1.25rem!important}#sidebar nav{display:flex!important;overflow-x:auto;gap:.5rem;margin-top:1rem!important;padding-bottom:.35rem}#sidebar .menu{width:auto!important;min-width:max-content;flex:0 0 auto;padding:.7rem .85rem}#sidebar>div:last-child{margin-top:1.25rem!important;padding-top:1rem!important}#dashboard>section{padding:1rem!important}#dashboard .grid{display:block!important}#recordForm{margin-bottom:1rem}#dashboard h1{font-size:1.7rem;line-height:1.15}#dashboard .card{border-radius:1.25rem}#dashboard table{min-width:40rem}#dashboard input,#dashboard select{font-size:16px}.toast{left:1rem;right:1rem;bottom:1rem}}
@media(min-width:768px) and (max-width:1023px){#sidebar{width:13.5rem!important}#dashboard>section{padding:1.5rem!important}#dashboard .grid{grid-template-columns:1fr 1.5fr!important}#dashboard table{min-width:38rem}}
`;

const PAYMENT_PANEL = `
<button id="paymentHelpBtn" class="fixed bottom-5 left-5 z-20 rounded-full px-5 py-3 text-sm font-bold text-white shadow-lg" style="background:var(--primary)">Pembayaran</button>
<div id="paymentModal" class="is-hidden fixed inset-0 z-30 grid place-items-center bg-slate-950/60 p-4"><div class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold" style="color:var(--primary)">INSTRUKSI PEMBAYARAN</p><h2 class="mt-1 text-2xl font-black">Pilih metode pembayaran</h2></div><button id="paymentCloseBtn" class="rounded-xl bg-slate-100 px-3 py-2 font-bold">Tutup</button></div><div id="paymentMethods" class="mt-5 space-y-3"><p class="text-sm text-slate-500">Memuat metode pembayaran…</p></div><div class="mt-6 flex gap-3"><button id="paymentShareBtn" class="flex-1 rounded-xl bg-slate-900 px-4 py-3 font-bold text-white">Bagikan</button><button id="paymentPrintBtn" class="flex-1 rounded-xl border px-4 py-3 font-bold">Cetak</button></div></div></div>
<script>(function(){const $=id=>document.getElementById(id);let methods=[];const esc=v=>String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));function render(){const host=$('paymentMethods');if(!methods.length){host.innerHTML='<p class="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Admin belum mengatur metode pembayaran.</p>';return}host.innerHTML=methods.map(m=>{const q=/^https:\/\//i.test(m.qrisUrl||'')?'<img class="mt-3 max-h-56 rounded-xl border" src="'+esc(m.qrisUrl)+'" alt="QRIS resmi '+esc(m.nama)+'">':'';return'<article class="rounded-2xl border p-4"><b>'+esc(m.jenis)+' • '+esc(m.nama)+'</b><p class="mt-1 text-sm">'+esc(m.penerima)+'</p><p class="font-mono text-sm font-bold">'+esc(m.nomor)+'</p>'+q+'<p class="mt-3 text-sm text-slate-600">'+esc(m.instruksi)+'</p></article>'}).join('')}function open(){ $('paymentModal').classList.remove('is-hidden');google.script.run.withSuccessHandler(r=>{methods=r.success?r.data:[];render()}).apiGetPaymentMethods()}function close(){$('paymentModal').classList.add('is-hidden')}function text(){return methods.map(m=>m.jenis+' - '+m.nama+'\\nPenerima: '+m.penerima+'\\nNomor: '+m.nomor+'\\n'+m.instruksi).join('\\n\\n')}$('paymentHelpBtn').onclick=open;$('paymentCloseBtn').onclick=close;$('paymentModal').onclick=e=>{if(e.target===$('paymentModal'))close()};$('paymentShareBtn').onclick=()=>{const t=text();if(navigator.share)navigator.share({title:'Instruksi Pembayaran',text:t});else navigator.clipboard.writeText(t).then(()=>alert('Instruksi pembayaran disalin.'))};$('paymentPrintBtn').onclick=()=>{const w=open('','_blank');w.document.write('<pre style="font:14px system-ui;white-space:pre-wrap">'+esc(text())+'</pre>');w.print()}})();</script>`;

const PAYMENT_PRINT_FIX = `<script>document.getElementById('paymentPrintBtn').onclick=function(){window.print()};</script>`;

export function getAppHtmlTemplate(projectName, profile, theme) {
  const specializedLayouts = { workshop: 'workshop' };
  const layout = specializedLayouts[profile.id] || theme.layout;
  const html = getBaseAppHtmlTemplate(projectName, profile, theme);
  return html
    .replace('</head>', `<style>${LAYOUT_CSS}</style></head>`)
    .replace('<body>', `<body class="dash-${layout}">`)
    .replace('</body>', `${PAYMENT_PANEL}${PAYMENT_PRINT_FIX}</body>`);
}
