export function getDatabaseGsTemplate(projectName, profile) {
  const modules = JSON.stringify(profile.modules).replace(/</g, '\\u003c');
  const safeProjectName = projectName.replace(/'/g, "\\'");
  return `/** ${safeProjectName} — database modular */
const APP_MODULES = ${modules};
const USER_SHEET = 'Users';

function DB_getSpreadsheet() {
  const props = PropertiesService.getScriptProperties();
  let id = props.getProperty('DB_SPREADSHEET_ID');
  if (!id) { const ss = SpreadsheetApp.create('${safeProjectName} - Database'); props.setProperty('DB_SPREADSHEET_ID', ss.getId()); return ss; }
  return SpreadsheetApp.openById(id);
}
function DB_sheetName_(module) { return 'Data - ' + module.name; }
function DB_module_(moduleId) { for (let i = 0; i < APP_MODULES.length; i++) if (APP_MODULES[i].id === moduleId) return APP_MODULES[i]; throw new Error('Modul tidak ditemukan.'); }
function DB_initSchema() {
  const lock = LockService.getScriptLock(); lock.waitLock(30000);
  try {
    const ss = DB_getSpreadsheet();
    const users = DB_ensureSheet_(ss, USER_SHEET, ['UserId', 'Username', 'PasswordHash', 'FullName', 'Role', 'CreatedAt']);
    APP_MODULES.forEach(function(module) { DB_ensureSheet_(ss, DB_sheetName_(module), ['Id'].concat(module.fields.map(function(f) { return f.label; })).concat(['Dibuat pada', 'Dibuat oleh'])); });
    DB_ensureAdmin_(users);
    const sheet1 = ss.getSheetByName('Sheet1'); if (sheet1 && ss.getSheets().length > 1) ss.deleteSheet(sheet1);
  } finally { lock.releaseLock(); }
}
function DB_ensureSheet_(ss, name, headers) { let sh = ss.getSheetByName(name); if (!sh) sh = ss.insertSheet(name); if (sh.getLastRow() === 0) { sh.appendRow(headers); sh.setFrozenRows(1); sh.getRange(1, 1, 1, headers.length).setFontWeight('bold'); } return sh; }
function DB_sheet_(name) { const ss = DB_getSpreadsheet(); let sh = ss.getSheetByName(name); if (!sh) { DB_initSchema(); sh = DB_getSpreadsheet().getSheetByName(name); } return sh; }
function DB_id_() { return Utilities.getUuid().split('-')[0].toUpperCase(); }
function DB_hash_(password) { return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password, Utilities.Charset.UTF_8).map(function(b) { return ('0' + (b < 0 ? b + 256 : b).toString(16)).slice(-2); }).join(''); }
function DB_ensureAdmin_(users) { const rows = users.getDataRange().getValues(); for (let i = 1; i < rows.length; i++) if (String(rows[i][1]) === 'Admin') return; users.appendRow([DB_id_(), 'Admin', DB_hash_('Admin123'), 'Administrator', 'admin', new Date()]); }
function AUTH_register(p) { const sh = DB_sheet_(USER_SHEET); DB_ensureAdmin_(sh); const rows = sh.getDataRange().getValues(); for (let i = 1; i < rows.length; i++) if (rows[i][1] === p.username) return { success:false, message:'Username sudah digunakan.' }; sh.appendRow([DB_id_(), p.username, DB_hash_(p.password), p.fullName || p.username, 'member', new Date()]); return { success:true, message:'Akun berhasil dibuat.' }; }
function AUTH_login(username, password) { const sh = DB_sheet_(USER_SHEET); DB_ensureAdmin_(sh); const rows = sh.getDataRange().getValues(), hash = DB_hash_(password); for (let i = 1; i < rows.length; i++) if (rows[i][1] === username && rows[i][2] === hash) return { success:true, user:{ id:rows[i][0], name:rows[i][3], username:rows[i][1], role:rows[i][4] } }; return { success:false, message:'Username atau password salah. Gunakan huruf besar yang tepat pada akun default: Admin / Admin123.' }; }
function AUTH_admin_(username, password) { const login = AUTH_login(username, password); if (!login.success || login.user.role !== 'admin') throw new Error('Konfirmasi password Admin diperlukan.'); return login.user; }
function DB_updateMyAccount(payload) { const username = String(payload.username || '').trim(), currentPassword = String(payload.currentPassword || ''), fullName = String(payload.fullName || '').trim(), newPassword = String(payload.newPassword || ''); if (!username || !currentPassword) throw new Error('Masukkan password saat ini untuk menyimpan perubahan.'); if (!fullName) throw new Error('Nama lengkap wajib diisi.'); if (newPassword && newPassword.length < 8) throw new Error('Password baru minimal 8 karakter.'); const sh = DB_sheet_(USER_SHEET), rows = sh.getDataRange().getValues(), hash = DB_hash_(currentPassword); for (let i = 1; i < rows.length; i++) { if (rows[i][1] === username && rows[i][2] === hash) { sh.getRange(i + 1, 4).setValue(fullName); if (newPassword) sh.getRange(i + 1, 3).setValue(DB_hash_(newPassword)); return { success:true, message:'Informasi akun berhasil diperbarui.', user:{ id:rows[i][0], username:username, name:fullName, role:rows[i][4] } }; } } return { success:false, message:'Password saat ini tidak sesuai.' }; }
function DB_getUsers(adminUsername, adminPassword) { AUTH_admin_(adminUsername, adminPassword); const rows = DB_sheet_(USER_SHEET).getDataRange().getDisplayValues(); rows.shift(); return { success:true, data:rows.map(function(row) { return { id:row[0], username:row[1], fullName:row[3], role:row[4], createdAt:row[5] }; }) }; }
function DB_adminUpdateUser(payload) { AUTH_admin_(payload.adminUsername, payload.adminPassword); const targetUsername = String(payload.targetUsername || '').trim(), fullName = String(payload.fullName || '').trim(), role = String(payload.role || 'member'), newPassword = String(payload.newPassword || ''); if (!targetUsername || !fullName) throw new Error('Username target dan nama lengkap wajib diisi.'); if (role !== 'admin' && role !== 'member') throw new Error('Role tidak valid.'); if (newPassword && newPassword.length < 8) throw new Error('Password reset minimal 8 karakter.'); const sh = DB_sheet_(USER_SHEET), rows = sh.getDataRange().getValues(); for (let i = 1; i < rows.length; i++) { if (rows[i][1] === targetUsername) { sh.getRange(i + 1, 4).setValue(fullName); sh.getRange(i + 1, 5).setValue(role); if (newPassword) sh.getRange(i + 1, 3).setValue(DB_hash_(newPassword)); return { success:true, message:'Data pengguna berhasil diperbarui.' }; } } return { success:false, message:'Pengguna tidak ditemukan.' }; }
function DB_saveRecord(payload) { const module = DB_module_(payload.moduleId); if (module.adminOnly && payload.userRole !== 'admin') return { success:false, message:'Modul ini hanya dapat diakses Admin.' }; if (module.id === 'order' && module.name === 'Order Laundry') { const berat = Number(payload.berat || 0), harga = Number(payload.harga || 0), diskon = Number(payload.diskon || 0); payload.total = Math.max(0, berat * harga - diskon); } const sh = DB_sheet_(DB_sheetName_(module)); const values = module.fields.map(function(f) { return payload[f.key] || ''; }); sh.appendRow([DB_id_()].concat(values, [new Date(), payload.userName || ''])); return { success:true, message:module.name + ' berhasil disimpan.' }; }
function DB_getDashboard(moduleId, userRole) { const module = DB_module_(moduleId); if (module.adminOnly && userRole !== 'admin') return { success:false, message:'Modul ini hanya dapat diakses Admin.' }; const sh = DB_sheet_(DB_sheetName_(module)), rows = sh.getDataRange().getDisplayValues(), headers = rows.shift() || []; return { success:true, data:{ module:module.name, total:rows.length, headers:headers, records:rows.slice(-12).reverse() } }; }
function DB_getOverview(userRole) { const summaries = [], recent = []; APP_MODULES.forEach(function(module) { if (module.adminOnly && userRole !== 'admin') return; const sh = DB_sheet_(DB_sheetName_(module)), values = sh.getDataRange().getValues(), headers = values.shift() || [], createdAtIndex = headers.indexOf('Dibuat pada'), createdByIndex = headers.indexOf('Dibuat oleh'); summaries.push({ id:module.id, name:module.name, icon:module.icon || '', total:values.length }); values.slice(-5).forEach(function(row) { const createdAt = createdAtIndex >= 0 ? row[createdAtIndex] : null; recent.push({ module:module.name, createdAt:createdAt instanceof Date ? createdAt.getTime() : 0, createdAtLabel:createdAt instanceof Date ? Utilities.formatDate(createdAt, Session.getScriptTimeZone(), 'dd/MM/yyyy HH:mm') : '-', createdBy:createdByIndex >= 0 ? String(row[createdByIndex] || '-') : '-' }); }); }); recent.sort(function(a, b) { return b.createdAt - a.createdAt; }); const total = summaries.reduce(function(sum, item) { return sum + item.total; }, 0); return { success:true, data:{ total:total, modules:summaries, recent:recent.slice(0,6) } }; }
function DB_getPaymentMethods() { const module = DB_module_('metodePembayaran'); const rows = DB_sheet_(DB_sheetName_(module)).getDataRange().getDisplayValues(); rows.shift(); return rows.slice(-20).reverse().map(function(row) { return { jenis: row[1], nama: row[2], penerima: row[3], nomor: row[4], qrisUrl: row[5], instruksi: row[6] }; }); }
`;
}
