const PROFILES = {
  attendance: { name: 'Absensi & SPP', icon: '✓', tagline: 'Kelola kehadiran dan pembayaran dalam satu tempat.', recordLabel: 'Aktivitas', sheetName: 'Aktivitas', fields: [{ key: 'jenis', label: 'Jenis absensi', type: 'select', options: ['Masuk', 'Pulang', 'Izin', 'Sakit'] }, { key: 'catatan', label: 'Catatan', type: 'text' }] },
  inventory: { name: 'Inventaris', icon: '▣', tagline: 'Pantau stok, aset, dan pergerakan barang secara rapi.', recordLabel: 'Pergerakan stok', sheetName: 'Stok', fields: [{ key: 'barang', label: 'Nama barang', type: 'text' }, { key: 'jumlah', label: 'Jumlah', type: 'number' }, { key: 'jenis', label: 'Jenis transaksi', type: 'select', options: ['Barang masuk', 'Barang keluar', 'Penyesuaian'] }, { key: 'catatan', label: 'Catatan', type: 'text' }] },
  cashier: { name: 'Kasir', icon: 'Rp', tagline: 'Catat transaksi penjualan dengan cepat dan sederhana.', recordLabel: 'Transaksi', sheetName: 'Transaksi', fields: [{ key: 'produk', label: 'Produk / layanan', type: 'text' }, { key: 'jumlah', label: 'Jumlah', type: 'number' }, { key: 'total', label: 'Total (Rp)', type: 'number' }, { key: 'metode', label: 'Metode bayar', type: 'select', options: ['Tunai', 'QRIS', 'Transfer', 'Kartu'] }] },
  booking: { name: 'Booking', icon: '◷', tagline: 'Atur jadwal dan kelola reservasi pelanggan tanpa tumpang tindih.', recordLabel: 'Reservasi', sheetName: 'Reservasi', fields: [{ key: 'pelanggan', label: 'Nama pelanggan', type: 'text' }, { key: 'layanan', label: 'Layanan', type: 'text' }, { key: 'jadwal', label: 'Tanggal & waktu', type: 'datetime-local' }, { key: 'status', label: 'Status', type: 'select', options: ['Menunggu', 'Dikonfirmasi', 'Selesai', 'Dibatalkan'] }] },
  service: { name: 'Layanan / Service', icon: '⚙', tagline: 'Terima, pantau, dan selesaikan pekerjaan layanan pelanggan.', recordLabel: 'Tiket service', sheetName: 'Tiket Service', fields: [{ key: 'pelanggan', label: 'Nama pelanggan', type: 'text' }, { key: 'keluhan', label: 'Keluhan / pekerjaan', type: 'text' }, { key: 'status', label: 'Status', type: 'select', options: ['Baru', 'Diproses', 'Selesai'] }, { key: 'biaya', label: 'Estimasi biaya', type: 'number' }] },
  crm: { name: 'Pelanggan / CRM', icon: '♙', tagline: 'Simpan prospek dan tindak lanjut pelanggan dari satu dashboard.', recordLabel: 'Aktivitas pelanggan', sheetName: 'Pelanggan', fields: [{ key: 'nama', label: 'Nama pelanggan', type: 'text' }, { key: 'kontak', label: 'Kontak', type: 'text' }, { key: 'tahap', label: 'Tahap', type: 'select', options: ['Prospek', 'Dihubungi', 'Negosiasi', 'Pelanggan'] }, { key: 'catatan', label: 'Catatan', type: 'text' }] },
  laundry: { name: 'Laundry', icon: '◉', tagline: 'Kelola cucian pelanggan, layanan, dan status pengerjaan.', recordLabel: 'Order laundry', sheetName: 'Order Laundry', fields: [{ key: 'pelanggan', label: 'Nama pelanggan', type: 'text' }, { key: 'layanan', label: 'Layanan', type: 'select', options: ['Cuci kiloan', 'Cuci satuan', 'Setrika', 'Express'] }, { key: 'berat', label: 'Berat (kg)', type: 'number' }, { key: 'status', label: 'Status', type: 'select', options: ['Diterima', 'Dicuci', 'Siap diambil', 'Selesai'] }] },
  rental: { name: 'Rental', icon: '◆', tagline: 'Catat penyewaan aset dan pantau tanggal pengembaliannya.', recordLabel: 'Penyewaan', sheetName: 'Penyewaan', fields: [{ key: 'penyewa', label: 'Nama penyewa', type: 'text' }, { key: 'item', label: 'Barang / aset', type: 'text' }, { key: 'kembali', label: 'Batas pengembalian', type: 'datetime-local' }, { key: 'status', label: 'Status', type: 'select', options: ['Dipinjam', 'Dikembalikan', 'Terlambat'] }] },
  clinic: { name: 'Klinik', icon: '+', tagline: 'Kelola antrean dan kunjungan pasien secara sederhana.', recordLabel: 'Kunjungan pasien', sheetName: 'Kunjungan', fields: [{ key: 'pasien', label: 'Nama pasien', type: 'text' }, { key: 'keluhan', label: 'Keluhan', type: 'text' }, { key: 'jadwal', label: 'Jadwal kunjungan', type: 'datetime-local' }, { key: 'status', label: 'Status', type: 'select', options: ['Menunggu', 'Diperiksa', 'Selesai'] }] },
  tasks: { name: 'Manajemen Tugas', icon: '✓', tagline: 'Susun pekerjaan tim dan pantau progres setiap tugas.', recordLabel: 'Tugas', sheetName: 'Tugas', fields: [{ key: 'tugas', label: 'Nama tugas', type: 'text' }, { key: 'penanggungJawab', label: 'Penanggung jawab', type: 'text' }, { key: 'deadline', label: 'Deadline', type: 'datetime-local' }, { key: 'status', label: 'Status', type: 'select', options: ['To do', 'Dikerjakan', 'Selesai'] }] },
  event: { name: 'Event Organizer', icon: '★', tagline: 'Atur agenda acara, klien, dan status persiapan event.', recordLabel: 'Agenda event', sheetName: 'Agenda Event', fields: [{ key: 'klien', label: 'Nama klien', type: 'text' }, { key: 'acara', label: 'Nama acara', type: 'text' }, { key: 'tanggal', label: 'Tanggal acara', type: 'datetime-local' }, { key: 'status', label: 'Status', type: 'select', options: ['Rencana', 'Persiapan', 'Berlangsung', 'Selesai'] }] }
};

export const PROJECT_TYPE_CHOICES = Object.entries(PROFILES).map(([value, profile]) => ({ name: profile.name, value }));

export function getProjectProfile(type) {
  return { id: type, ...(PROFILES[type] || PROFILES.attendance) };
}
